import mongoose from "mongoose";

const dailyClosingSchema = new mongoose.Schema(
  {
    // ==================================================
    // PUMP
    // ==================================================
    pumpId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Pump",
      required: true,
      immutable: true,
    },

    // ==================================================
    // BUSINESS DATE
    // ==================================================
    /*
     * Business date generated by the controller
     * using BUSINESS_TIMEZONE.
     *
     * Format:
     * YYYY-MM-DD
     */
    businessDate: {
      type: String,
      required: true,
      trim: true,
      match: /^\d{4}-\d{2}-\d{2}$/,
      immutable: true,
    },

    // ==================================================
    // SALES
    // ==================================================
    totalSales: {
      type: Number,
      default: 0,
      min: 0,
    },

    cashSales: {
      type: Number,
      default: 0,
      min: 0,
    },

    upiSales: {
      type: Number,
      default: 0,
      min: 0,
    },

    cardSales: {
      type: Number,
      default: 0,
      min: 0,
    },

    creditSales: {
      type: Number,
      default: 0,
      min: 0,
    },

    // ==================================================
    // EXPENSES / COLLECTION
    // ==================================================
    totalExpenses: {
      type: Number,
      default: 0,
      min: 0,
    },

    netCollection: {
      type: Number,
      default: 0,
    },

    // ==================================================
    // FUEL SALES
    // ==================================================
    petrolSold: {
      type: Number,
      default: 0,
      min: 0,
    },

    dieselSold: {
      type: Number,
      default: 0,
      min: 0,
    },

    // ==================================================
    // CLOSING STOCK
    // ==================================================
    petrolClosingStock: {
      type: Number,
      default: 0,
      min: 0,
    },

    dieselClosingStock: {
      type: Number,
      default: 0,
      min: 0,
    },

    // ==================================================
    // CREDIT
    // ==================================================
    pendingCredit: {
      type: Number,
      default: 0,
      min: 0,
    },

    // ==================================================
    // STATUS
    // ==================================================
    status: {
      type: String,
      enum: ["closed", "reopened"],
      default: "closed",
      lowercase: true,
      trim: true,
    },

    // ==================================================
    // CLOSING USER
    // ==================================================
    closedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      immutable: true,
    },

    closedAt: {
      type: Date,
      default: Date.now,
    },

    // ==================================================
    // REOPEN INFORMATION
    // ==================================================
    reopenedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    reopenedAt: {
      type: Date,
      default: null,
    },

    // ==================================================
    // NOTE
    // ==================================================
    note: {
      type: String,
      default: "",
      trim: true,
      maxlength: 2000,
    },
  },
  {
    timestamps: true,
    strict: true,
  }
);

/* =====================================================
   INDEXES
===================================================== */

/*
 * CRITICAL INDEX
 *
 * One closing per pump per business date.
 *
 * Also directly supports:
 *
 * DailyClosing.findOne({
 *   pumpId,
 *   businessDate
 * })
 */
dailyClosingSchema.index(
  {
    pumpId: 1,
    businessDate: 1,
  },
  {
    unique: true,
    name: "uniq_daily_closing_pump_date",
  }
);

/*
 * Daily closing history.
 *
 * Example:
 *
 * DailyClosing.find({
 *   pumpId
 * }).sort({
 *   businessDate: -1
 * })
 */
dailyClosingSchema.index(
  {
    pumpId: 1,
    businessDate: -1,
  },
  {
    name: "idx_daily_closing_pump_date",
  }
);

/*
 * Find reopened days for a pump.
 */
dailyClosingSchema.index(
  {
    pumpId: 1,
    status: 1,
    businessDate: -1,
  },
  {
    name: "idx_daily_closing_status",
  }
);

/*
 * User closing history / audit queries.
 */
dailyClosingSchema.index(
  {
    pumpId: 1,
    closedBy: 1,
    closedAt: -1,
  },
  {
    name: "idx_daily_closing_user",
  }
);

/* =====================================================
   MODEL
===================================================== */

const DailyClosing =
  mongoose.models.DailyClosing ||
  mongoose.model(
    "DailyClosing",
    dailyClosingSchema
  );

export default DailyClosing;